/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./layout/components/AppHeader/index.vue')['default']
    AppHeaderComponentsBreadcrumb: typeof import('./layout/components/AppHeader/components/Breadcrumb/index.vue')['default']
    AppHeaderComponentsHamburger: typeof import('./layout/components/AppHeader/components/Hamburger/index.vue')['default']
    AppHeaderComponentsScreenfull: typeof import('./layout/components/AppHeader/components/Screenfull/index.vue')['default']
    AppMain: typeof import('./layout/components/AppMain/index.vue')['default']
    CustomFormSrc: typeof import('./components/CustomForm/src/index.vue')['default']
    CustomTableSrc: typeof import('./components/CustomTable/src/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FormDialogSrc: typeof import('./components/FormDialog/src/index.vue')['default']
    InputNumberSrc: typeof import('./components/InputNumber/src/index.vue')['default']
    ModalDialogSrc: typeof import('./components/ModalDialog/src/index.vue')['default']
    PaginationSrc: typeof import('./components/Pagination/src/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./layout/components/Sidebar/index.vue')['default']
    SidebarSideBarItem: typeof import('./layout/components/Sidebar/SideBarItem.vue')['default']
    SvgIconSrc: typeof import('./components/SvgIcon/src/index.vue')['default']
    TagsView: typeof import('./layout/components/TagsView/index.vue')['default']
    TagsViewTagViewItem: typeof import('./layout/components/TagsView/TagViewItem.vue')['default']
    TreeSelectSrc: typeof import('./components/TreeSelect/src/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
